//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Stealth
{
    [Serializable]
    public class StealthMsg : Message
    {
        public const string k_RosMessageName = "stealth_msgs/Stealth";
        public override string RosMessageName => k_RosMessageName;

        public float[] distance;
        public float[] observation_time;
        public float[] intensity;

        public StealthMsg()
        {
            this.distance = new float[0];
            this.observation_time = new float[0];
            this.intensity = new float[0];
        }

        public StealthMsg(float[] distance, float[] observation_time, float[] intensity)
        {
            this.distance = distance;
            this.observation_time = observation_time;
            this.intensity = intensity;
        }

        public static StealthMsg Deserialize(MessageDeserializer deserializer) => new StealthMsg(deserializer);

        private StealthMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.distance, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.observation_time, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.intensity, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.distance);
            serializer.Write(this.distance);
            serializer.WriteLength(this.observation_time);
            serializer.Write(this.observation_time);
            serializer.WriteLength(this.intensity);
            serializer.Write(this.intensity);
        }

        public override string ToString()
        {
            return "StealthMsg: " +
            "\ndistance: " + System.String.Join(", ", distance.ToList()) +
            "\nobservation_time: " + System.String.Join(", ", observation_time.ToList()) +
            "\nintensity: " + System.String.Join(", ", intensity.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
